-- AlterTable
ALTER TABLE "AppTheme" ALTER COLUMN "ink" SET DEFAULT '#1e232e',
ALTER COLUMN "pageBg" SET DEFAULT '#0b0d12',
ALTER COLUMN "surface" SET DEFAULT '#12151c',
ALTER COLUMN "border" SET DEFAULT '#262b36',
ALTER COLUMN "accent" SET DEFAULT '#ffd400',
ALTER COLUMN "headingFont" SET DEFAULT 'BigShoulders',
ALTER COLUMN "radius" SET DEFAULT 0;
